micronaut:
  application:
    name: test-jdbc-demo
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    schema-generate: NONE
    dialect: POSTGRES
    url: r2dbc:postgresql://localhost:5432/r2-dictionary
    username: postgres
    password: ZSE4zse4
