CREATE TABLE "dictionary"
(
    id int PRIMARY KEY GENERATED BY DEFAULT AS identity,
    "name" varchar(255)  NOT NULL,
    unique ("name")
);

-- CREATE TABLE dictionary_value
-- (
--     id int PRIMARY KEY GENERATED BY DEFAULT AS identity,
--     code          varchar(255)  NOT NULL,
--     value         varchar(255)  NOT NULL,
--     dictionary_id int NULL references "dictionary" (id),
--     primary key (id)
-- );